// Auto-generated — do not edit by hand
export const targetCharacterMap = {
  "sonic": "sonic-the-hedgehog",
  "sonic the hedgehog": "sonic-the-hedgehog",
  "doctor": "doctor-eggman",
  "doctor eggman": "doctor-eggman",
  "eggman": "doctor-eggman",
  "robotnik": "doctor-eggman",
  "ivo": "doctor-eggman",
  "doctor robotnik": "doctor-eggman",
  "dr eggman": "doctor-eggman",
  "dr. eggman": "doctor-eggman",
  "dr robotnik": "doctor-eggman",
  "dr. robotnik": "doctor-eggman",
  "miles": "miles-tails-prower",
  "miles tails prower": "miles-tails-prower",
  "tails": "miles-tails-prower",
  "amy": "amy-rose",
  "amy rose": "amy-rose",
  "rose": "amy-rose",
  "rosy the rascal": "amy-rose",
  "princess sally": "amy-rose",
  "sally": "amy-rose",
  "metal": "metal-sonic",
  "metal sonic": "metal-sonic",
  "knuckles": "knuckles-the-echidna",
  "knuckles the echidna": "knuckles-the-echidna",
  "vector": "vector-the-crocodile",
  "vector the crocodile": "vector-the-crocodile",
  "espio": "espio-the-chameleon",
  "espio the chameleon": "espio-the-chameleon",
  "shadow": "shadow-the-hedgehog",
  "shadow the hedgehog": "shadow-the-hedgehog",
  "ultimate life form": "shadow-the-hedgehog",
  "the ultimate life form": "shadow-the-hedgehog",
  "rouge": "rouge-the-bat",
  "rouge the bat": "rouge-the-bat"
};
