// Auto-generated — do not edit by hand
export const targetCharacterMap = {
  "sonic": "sonic-the-hedgehog",
  "sonic the hedgehog": "sonic-the-hedgehog",
  "sonic-the-hedgehog": "sonic-the-hedgehog",
  "doctor": "doctor-eggman",
  "doctor eggman": "doctor-eggman",
  "doctor-eggman": "doctor-eggman",
  "miles": "miles-tails-prower",
  "miles tails prower": "miles-tails-prower",
  "miles-tails-prower": "miles-tails-prower",
  "amy": "amy-rose",
  "amy rose": "amy-rose",
  "amy-rose": "amy-rose",
  "metal": "metal-sonic",
  "metal sonic": "metal-sonic",
  "metal-sonic": "metal-sonic",
  "knuckles": "knuckles-the-echidna",
  "knuckles the echidna": "knuckles-the-echidna",
  "knuckles-the-echidna": "knuckles-the-echidna",
  "vector": "vector-the-crocodile",
  "vector the crocodile": "vector-the-crocodile",
  "vector-the-crocodile": "vector-the-crocodile",
  "espio": "espio-the-chameleon",
  "espio the chameleon": "espio-the-chameleon",
  "espio-the-chameleon": "espio-the-chameleon",
  "shadow": "shadow-the-hedgehog",
  "shadow the hedgehog": "shadow-the-hedgehog",
  "shadow-the-hedgehog": "shadow-the-hedgehog",
  "rouge": "rouge-the-bat",
  "rouge the bat": "rouge-the-bat",
  "rouge-the-bat": "rouge-the-bat",
  "tonic": "tonic-the-zonic",
  "tonic the zonic": "tonic-the-zonic",
  "tonic-the-zonic": "tonic-the-zonic"
};
